services:
    _defaults:
        autowire: true
        autoconfigure: true



    Santeacademie\SuperUploaderBundle\Twig\UploaderTwigExtension:
        arguments:
            - '%super_voter.twig_globals_enabled%'
